version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8100:80"
        container_name: merchants_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: merchants_app
        depends_on:
            - db
    db:
        image: postgres:latest
        restart: always
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT:-5432}:5432
        env_file:
            - .env
        container_name: merchants_db

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"

volumes:
    pg_project:
